image: maven:latest

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'

stages:
    - package

package-job:
    stage: package
    tags: 
        - docker
    
    script:
        - echo "Maven build started"
        - "mvn -f shusherGUI clean package"
        - echo "Maven build finished"

