image: maven:latest

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'

stages:
    - package
    - release

package-job:
    stage: package
    tags: 
        - docker
    
    script:
        - echo "Maven build started"
        - "mvn -f shusherGUI clean package"
        - echo "Maven build finished"

release-job:
    stage: release
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

    script:
        - echo "Running release job for shusherGUI"
        - apt-get update && apt-get install -y openjdk-8-jdk  # Install Java 8
        - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64  # Set the Java home directory
        - export PATH=$PATH:$JAVA_HOME/bin  # Add Java to the PATH
        - export PATH=$PATH:/usr/local/bin  # Add /usr/local/bin to the PATH
        - release-cli create --description "v0.$CI_PIPELINE_IID" --tag-name "v0.$CI_PIPELINE_IID" --ref "$CI_COMMIT_SHA"
    release:
        tag_name: 'v0.$CI_PIPELINE_IID'
        description: 'v0.$CI_PIPELINE_IID'
        ref: '$CI_COMMIT_SHA'
    artifacts:
        paths:
            - shusherGUI/shusherGUI-1.0.jar 
